### ISSUE TITLE
Create line chart

### ISSUE THREAD

**Issue by chen-chen-stat** [BR-Visualization/brcharts#5]
This is Figure 3 in the publication

![Image](https://github.com/BR-Visualization/charts/assets/38993208/b945b292-1c24-4382-b11c-8bf0fd5492d7)

**Comment by Lovemore-Gakava** [comment]
![Image](https://github.com/BR-Visualization/charts/assets/38993208/83e1e3e9-c7a6-4173-a25c-3ff84996961a)
